version: "3.7"

services: 
    jenkins:
        container_name: jenkins_funapi
        build: 
            context: .
            dockerfile: jenkins.dockerfile
        ports: 
            - 8080:8080
            - 50000:50000