FROM jenkins/jenkins:2.325

# Skip setup wizard
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false

# Install plugins 
COPY jenkins-plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

# Copy seed job
COPY seedjob.groovy /usr/local/seedjob.groovy

# Copy jenkins configuration file
COPY jenkins-configuration.yaml /var/jenkins_config/jenkins-configuration.yaml
ENV CASC_JENKINS_CONFIG /var/jenkins_config/jenkins-configuration.yaml

USER root

RUN apt-get update
RUN apt-get install wget

# install dot net sdk 5.0
RUN wget -q https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt-get update
RUN apt-get install apt-transport-https
RUN apt-get update
RUN apt-get install -y dotnet-sdk-5.0

# install docker cli
RUN apt-get -y install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

RUN echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN apt-get update

RUN apt-get -y install docker-ce-cli

USER jenkins