unclassified:
  location:
    url: ${JENKINS_URL}

jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy: 
      LoggedInUsersCanDoAnything:
        allowAnonymousRead: false
  remotingSecurity:
    enabled: true

jobs:
    - file: /usr/local/seedjob.groovy
